services:
  apiservice:
   image: "random-experiment" 
   container_name: random-experiment
   restart: unless-stopped
   environment:
       TZ: "Europe/Moscow"
   ports:
      - "${APISERVICE_PORT}"
   volumes:
      - /etc/localtime:/etc/localtime:ro

    